name: Generate

on:
  push:
    branches:
      - main
    paths:
      - "**.toml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: create_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: generate and commit/push
        uses: actions/checkout@v4
        run: |
          python toml2md.py
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f README.md README-ja.md
          git commit -m 'generate README.md'
          git push
        with:
          token: ${{ steps.create_token.outputs.token }}
