name: Generate

on:
  push:
    branches:
      - main
    paths:
      - "**.toml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Generate README.md
        run: |
          python toml2md.py

      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit and push
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f README.md README-ja.md
          git commit -m 'generate README.md'
          git push
        if: steps.diff.outcome == 'failure'
